import { useEffect } from "react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ShieldCheck, Zap, Lock, Eye } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const proofPoints = [
  { text: "Cannot be replayed", icon: ShieldCheck },
  { text: "Cannot be proxied", icon: Lock },
  { text: "Cannot be automated", icon: Zap },
  { text: "Cannot be generated by AI systems", icon: Eye },
];

const gains = [
  "Execution‑time human authorization for high‑risk actions",
  "Enforceable control inside autonomous workflows",
  "No passwords, push approvals, OTPs, biometrics, or hardware tokens",
  "No dependence on device trust, session integrity, or cloud availability",
  "AI‑resilient, post‑quantum ready cryptographic foundations",
  "Compatibility with existing IAM and identity platforms",
];

const failurePoints = [
  { text: "Accountability breaks", num: "01" },
  { text: "Non‑repudiation disappears", num: "02" },
  { text: "Errors scale into systemic failures", num: "03" },
];

const sectionFade = {
  initial: { opacity: 0, y: 20 } as const,
  whileInView: { opacity: 1, y: 0 } as const,
  viewport: { once: true, margin: "-60px" } as const,
  transition: { duration: 0.6 },
};

const AboutPage = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-background text-foreground">
      <Navbar />

      {/* ─── Hero ─── */}
      <section className="pt-32 pb-20 md:pt-40 md:pb-28 relative overflow-hidden">
        <div className="absolute inset-0 opacity-[0.03]" style={{
          backgroundImage: `linear-gradient(hsl(var(--foreground)) 1px, transparent 1px), linear-gradient(90deg, hsl(var(--foreground)) 1px, transparent 1px)`,
          backgroundSize: '60px 60px',
        }} />
        <div className="absolute top-1/2 right-0 -translate-y-1/2 w-[600px] h-[600px] rounded-full opacity-[0.03]" style={{
          background: 'radial-gradient(circle, hsl(var(--foreground)) 0%, transparent 70%)',
        }} />
        <div className="max-w-6xl mx-auto px-6 lg:px-8 relative">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.4, delay: 0.1 }}
            className="flex items-center gap-2 text-xs text-muted-foreground mb-10"
          >
            <Link to="/" className="hover:text-foreground transition-colors">Home</Link>
            <span className="text-border">/</span>
            <span className="text-foreground">About</span>
          </motion.div>

          <div className="grid lg:grid-cols-[1fr_1fr] gap-16 items-end">
            <div>
              <motion.div
                initial={{ opacity: 0, width: 0 }}
                animate={{ opacity: 1, width: "3rem" }}
                transition={{ duration: 0.8, delay: 0.15 }}
                className="h-px bg-foreground mb-6"
              />
              <motion.p
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.5, delay: 0.25 }}
                className="text-xs font-medium tracking-[0.2em] uppercase text-muted-foreground mb-5"
              >
                The QSVA Thesis
              </motion.p>
              <motion.h1
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.7, delay: 0.3 }}
                className="font-serif text-4xl md:text-5xl lg:text-6xl leading-[1.1] tracking-tight text-foreground"
              >
                Execution‑Time
                <br />
                Authorization
                <br />
                <span className="text-muted-foreground/50">for Agentic Systems</span>
              </motion.h1>
            </div>
            <motion.p
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.5 }}
              className="text-muted-foreground text-base md:text-lg leading-relaxed max-w-md lg:pb-2"
            >
              A comprehensive look at why agentic systems need a new authorization primitive — and how QSVA delivers it.
            </motion.p>
          </div>
        </div>
        <div className="absolute bottom-0 left-0 right-0 h-px bg-border" />
      </section>

      {/* ─── Part 1: The Problem ─── */}
      <section className="py-20 md:py-28">
        <div className="max-w-6xl mx-auto px-6 lg:px-8">
          <div className="grid lg:grid-cols-[280px_1fr] gap-12 lg:gap-20">
            <motion.div {...sectionFade} className="lg:sticky lg:top-28 lg:self-start">
              <div className="flex items-center gap-4 mb-4">
                <div className="h-px w-8 bg-foreground" />
                <span className="text-xs font-medium tracking-[0.2em] uppercase text-muted-foreground">01</span>
              </div>
              <h2 className="font-serif text-3xl md:text-4xl text-foreground">
                The Problem
              </h2>
            </motion.div>

            <motion.div {...sectionFade} className="max-w-2xl">
              <div className="space-y-6 text-muted-foreground leading-relaxed text-base md:text-lg">
                <p>
                  Agentic systems don't just execute commands — they decide what actions to take.
                </p>
                <p>
                  They initiate financial transfers, modify infrastructure, recover systems, spawn workflows,
                  and act across distributed environments without continuous human supervision.
                </p>
                <motion.p
                  {...sectionFade}
                  className="text-foreground font-medium text-xl md:text-2xl font-serif leading-snug py-4 border-l-2 border-foreground pl-6"
                >
                  This breaks the assumptions behind modern security.
                </motion.p>
                <p>
                  IAM, MFA, and device trust were designed for human‑initiated sessions, not for systems
                  that generate intent and execute actions autonomously.
                </p>
                <p>
                  As agentic systems scale, the question is no longer{" "}
                  <em className="text-foreground not-italic font-medium">who logged in</em> — it's{" "}
                  <em className="text-foreground not-italic font-medium">who approved this specific action at the moment it executed</em>.
                </p>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ─── Part 2: The Missing Control ─── */}
      <section className="py-20 md:py-28 bg-secondary relative overflow-hidden">
        <div className="absolute top-0 left-0 right-0 h-px bg-border" />
        <div className="max-w-6xl mx-auto px-6 lg:px-8">
          <div className="grid lg:grid-cols-[280px_1fr] gap-12 lg:gap-20">
            <motion.div {...sectionFade} className="lg:sticky lg:top-28 lg:self-start">
              <div className="flex items-center gap-4 mb-4">
                <div className="h-px w-8 bg-foreground" />
                <span className="text-xs font-medium tracking-[0.2em] uppercase text-muted-foreground">02</span>
              </div>
              <h2 className="font-serif text-3xl md:text-4xl text-foreground">
                The Gap
              </h2>
            </motion.div>

            <motion.div {...sectionFade} className="max-w-2xl">
              <h3 className="font-serif text-2xl md:text-3xl text-foreground mb-8">
                The Missing Control in Agentic Execution
              </h3>
              <div className="space-y-5 text-muted-foreground leading-relaxed text-base md:text-lg mb-12">
                <p>
                  Once access is granted, agentic systems operate inside trusted environments and execute
                  high‑risk, irreversible actions without cryptographic proof that a real human approved
                  them at execution time.
                </p>
                <p>
                  Guardrails, monitoring, and audit observe behavior.{" "}
                  <em className="text-foreground not-italic font-medium">They do not enforce human authorization when actions commit.</em>
                </p>
              </div>

              <p className="text-muted-foreground text-base md:text-lg mb-6">
                For agentic systems, this gap is existential:
              </p>

              <div className="grid sm:grid-cols-3 gap-px bg-border rounded-lg overflow-hidden mb-10">
                {failurePoints.map((point, i) => (
                  <motion.div
                    key={point.text}
                    initial={{ opacity: 0, y: 10 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.4, delay: i * 0.1 }}
                    className="bg-background p-6 text-center"
                  >
                    <span className="text-xs font-medium tracking-widest text-destructive/60 block mb-2">{point.num}</span>
                    <p className="text-sm font-medium text-foreground">{point.text}</p>
                  </motion.div>
                ))}
              </div>

              <motion.p
                {...sectionFade}
                className="text-foreground font-medium text-base md:text-lg"
              >
                QSVA exists to provide the control agentic systems require.
              </motion.p>
            </motion.div>
          </div>
        </div>
        <div className="absolute bottom-0 left-0 right-0 h-px bg-border" />
      </section>

      {/* ─── Part 3: Execution‑Time Trust ─── */}
      <section className="py-20 md:py-28">
        <div className="max-w-6xl mx-auto px-6 lg:px-8">
          <div className="grid lg:grid-cols-[280px_1fr] gap-12 lg:gap-20 mb-20">
            <motion.div {...sectionFade} className="lg:sticky lg:top-28 lg:self-start">
              <div className="flex items-center gap-4 mb-4">
                <div className="h-px w-8 bg-foreground" />
                <span className="text-xs font-medium tracking-[0.2em] uppercase text-muted-foreground">03</span>
              </div>
              <h2 className="font-serif text-3xl md:text-4xl text-foreground">
                A New Category
              </h2>
            </motion.div>

            <motion.div {...sectionFade} className="max-w-2xl">
              <h3 className="font-serif text-2xl md:text-3xl text-foreground mb-8">
                Execution‑Time Trust
              </h3>
              <div className="space-y-5 text-muted-foreground leading-relaxed text-base md:text-lg mb-10">
                <p>
                  QSVA introduces an authorization control architecture designed specifically for agentic systems.
                </p>
                <p>
                  It operates after access is granted and immediately before execution, where decisions become irreversible.
                </p>
                <p>
                  Instead of trusting sessions, devices, or prior authentication, QSVA cryptographically binds
                  a real human's approval to a specific action, producing proof that is:
                </p>
              </div>

              <div className="grid grid-cols-2 gap-px bg-border rounded-lg overflow-hidden max-w-sm mb-10">
                {["Verified in real time", "Auditable after execution"].map((item, i) => (
                  <motion.div
                    key={item}
                    initial={{ opacity: 0, scale: 0.95 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.4, delay: i * 0.1 }}
                    className="bg-secondary p-5"
                  >
                    <p className="text-sm font-medium text-foreground">{item}</p>
                  </motion.div>
                ))}
              </div>

              <p className="text-muted-foreground text-base md:text-lg leading-relaxed">
                This enables agentic systems to act autonomously until a boundary that requires human authority is reached.
              </p>
            </motion.div>
          </div>

          {/* Divider */}
          <div className="h-px bg-border mb-20" />

          {/* Two columns: How + What */}
          <div className="grid md:grid-cols-2 gap-16 md:gap-20">
            <motion.div {...sectionFade}>
              <h3 className="font-serif text-2xl md:text-3xl text-foreground mb-5">How QSVA Works</h3>
              <p className="text-muted-foreground mb-8 leading-relaxed">
                QSVA converts a human decision into cryptographic proof bound to a single action
                within an execution path. That proof:
              </p>
              <div className="space-y-4">
                {proofPoints.map((point, i) => (
                  <motion.div
                    key={point.text}
                    initial={{ opacity: 0, x: -15 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.4, delay: i * 0.1 }}
                    className="flex items-center gap-4 p-4 rounded-lg border border-border bg-secondary/50 hover:bg-secondary transition-colors duration-300"
                  >
                    <point.icon size={18} className="text-foreground/70 flex-shrink-0" />
                    <span className="text-sm font-medium text-foreground">{point.text}</span>
                  </motion.div>
                ))}
              </div>
            </motion.div>

            <motion.div
              {...sectionFade}
              transition={{ duration: 0.6, delay: 0.15 }}
            >
              <h3 className="font-serif text-2xl md:text-3xl text-foreground mb-5">What Agentic Systems Gain</h3>
              <ul className="space-y-5">
                {gains.map((gain, i) => (
                  <motion.li
                    key={gain}
                    initial={{ opacity: 0, x: -10 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.3, delay: i * 0.06 }}
                    className="flex items-start gap-4"
                  >
                    <span className="w-1.5 h-1.5 rounded-full bg-foreground flex-shrink-0 mt-2" />
                    <span className="text-sm text-muted-foreground leading-relaxed">{gain}</span>
                  </motion.li>
                ))}
              </ul>
            </motion.div>
          </div>

          {/* Callout */}
          <motion.div
            {...sectionFade}
            className="mt-20 max-w-3xl mx-auto text-center py-16 px-8"
          >
            <div className="flex justify-center mb-6">
              <div className="h-px w-12 bg-foreground" />
            </div>
            <p className="font-serif text-2xl md:text-3xl text-foreground leading-relaxed italic">
              "QSVA does not replace autonomy.
              <br />
              It defines the boundary where autonomy must stop."
            </p>
            <div className="flex justify-center mt-6">
              <div className="h-px w-12 bg-foreground" />
            </div>
          </motion.div>
        </div>
      </section>

      {/* ─── Part 4: Extending Zero Trust ─── */}
      <section className="py-20 md:py-28 bg-secondary relative">
        <div className="absolute top-0 left-0 right-0 h-px bg-border" />
        <div className="max-w-6xl mx-auto px-6 lg:px-8">
          <div className="grid lg:grid-cols-[280px_1fr] gap-12 lg:gap-20">
            <motion.div {...sectionFade} className="lg:sticky lg:top-28 lg:self-start">
              <div className="flex items-center gap-4 mb-4">
                <div className="h-px w-8 bg-foreground" />
                <span className="text-xs font-medium tracking-[0.2em] uppercase text-muted-foreground">04</span>
              </div>
              <h2 className="font-serif text-3xl md:text-4xl text-foreground">
                Zero Trust Extended
              </h2>
            </motion.div>

            <motion.div {...sectionFade} className="max-w-2xl">
              <h3 className="font-serif text-2xl md:text-3xl text-foreground mb-8">
                Extending Zero Trust into Agentic Execution
              </h3>
              <div className="space-y-5 text-muted-foreground leading-relaxed text-base md:text-lg">
                <p>
                  Zero Trust removed implicit trust at access boundaries.
                </p>
                <p>
                  Agentic systems require the same principle at execution time.
                </p>
                <p>
                  QSVA ensures that as autonomous systems operate at machine speed, human authority
                  remains cryptographically enforced at the moments that matter.
                </p>
              </div>

              <motion.p
                {...sectionFade}
                className="mt-10 text-foreground font-semibold text-lg md:text-xl border-t border-border pt-8 leading-relaxed"
              >
                QSVA is the execution‑time authorization architecture required for agentic systems to scale safely.
              </motion.p>

              <div className="mt-12 flex flex-col sm:flex-row gap-4">
                <a
                  href="https://calendly.com/ben-qsva/30min"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="group inline-flex items-center px-7 py-3.5 rounded-md bg-primary text-primary-foreground font-medium text-sm hover:bg-primary/90 transition-all duration-300 hover:shadow-lg hover:shadow-primary/10"
                >
                  Talk to the QSVA Team
                  <svg width="14" height="14" viewBox="0 0 16 16" fill="none" className="ml-2 transition-transform duration-300 group-hover:translate-x-1">
                    <path d="M3 8h10m0 0L9 4m4 4L9 12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                </a>
                <Link
                  to="/"
                  className="inline-flex items-center px-7 py-3.5 rounded-md border border-input text-foreground font-medium text-sm hover:bg-accent transition-all duration-300"
                >
                  ← Back to Home
                </Link>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default AboutPage;
