import { motion } from "framer-motion";

const proofPoints = [
  "Cannot be replayed",
  "Cannot be proxied",
  "Cannot be automated",
  "Cannot be generated by AI systems",
];

const gains = [
  "Execution‑time human authorization for high‑risk actions",
  "Enforceable control inside autonomous workflows",
  "No passwords, push approvals, OTPs, biometrics, or hardware tokens",
  "No dependence on device trust, session integrity, or cloud availability",
  "AI‑resilient, post‑quantum ready cryptographic foundations",
  "Compatibility with existing IAM and identity platforms",
];

const About = () => {
  return (
    <section id="about" className="py-24 md:py-32 relative">
      {/* Decorative vertical line */}
      <div className="absolute top-0 left-1/2 w-px h-24 bg-gradient-to-b from-transparent to-border hidden md:block" />

      <div className="max-w-6xl mx-auto px-6 lg:px-8">
        {/* Intro */}
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-80px" }}
          transition={{ duration: 0.5 }}
          className="max-w-3xl mb-20"
        >
          <div className="flex items-center gap-4 mb-4">
            <div className="h-px w-8 bg-foreground" />
            <span className="text-xs font-medium tracking-[0.2em] uppercase text-muted-foreground">The Problem</span>
          </div>
          <h2 className="font-serif text-4xl md:text-5xl text-foreground mb-8">
            About QSVA
          </h2>
          <div className="space-y-5 text-muted-foreground leading-relaxed text-base md:text-lg">
            <p>
              Agentic systems don't just execute commands — they decide what actions to take.
              They initiate financial transfers, modify infrastructure, recover systems, and act
              across distributed environments without continuous human supervision.
            </p>
            <p>
              IAM, MFA, and device trust were designed for human‑initiated sessions, not for systems
              that generate intent and execute actions autonomously. As agentic systems scale, the
              question is no longer <em className="text-foreground not-italic font-medium">who logged in</em> — it's{" "}
              <em className="text-foreground not-italic font-medium">who approved this specific action at the moment it executed</em>.
            </p>
          </div>
        </motion.div>

        {/* Divider */}
        <div className="h-px bg-border mb-20" />

        {/* Two columns */}
        <div className="grid md:grid-cols-2 gap-16 md:gap-24">
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-80px" }}
            transition={{ duration: 0.5 }}
          >
            <h3 className="font-serif text-2xl md:text-3xl text-foreground mb-5">How QSVA Works</h3>
            <p className="text-muted-foreground mb-8 leading-relaxed">
              QSVA converts a human decision into cryptographic proof bound to a single action
              within an execution path. That proof:
            </p>
            <ul className="space-y-5">
              {proofPoints.map((point, i) => (
                <motion.li
                  key={point}
                  initial={{ opacity: 0, x: -10 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.3, delay: i * 0.08 }}
                  className="flex items-center gap-4"
                >
                  <span className="w-6 h-px bg-foreground flex-shrink-0" />
                  <span className="text-sm font-medium text-foreground">{point}</span>
                </motion.li>
              ))}
            </ul>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-80px" }}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            <h3 className="font-serif text-2xl md:text-3xl text-foreground mb-5">What Systems Gain</h3>
            <ul className="space-y-5">
              {gains.map((gain, i) => (
                <motion.li
                  key={gain}
                  initial={{ opacity: 0, x: -10 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.3, delay: i * 0.06 }}
                  className="flex items-start gap-4"
                >
                  <span className="w-6 h-px bg-muted-foreground flex-shrink-0 mt-2.5" />
                  <span className="text-sm text-muted-foreground leading-relaxed">{gain}</span>
                </motion.li>
              ))}
            </ul>
          </motion.div>
        </div>

        {/* Callout */}
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="mt-24 border-l-2 border-foreground pl-8 py-2 max-w-3xl"
        >
          <p className="font-serif text-xl md:text-2xl text-foreground leading-relaxed italic">
            "QSVA does not replace autonomy.
            It defines the boundary where autonomy must stop."
          </p>
        </motion.div>
      </div>
    </section>
  );
};

export default About;
